{% set name = "chex" %}
{% set version = "0.1.90" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chex-{{ version }}.tar.gz
  sha256: d3c375aeb6154b08f1cccd2bee4ed83659ee2198a6acf1160d2fe2e4a6c87b5c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolatio

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - typing_extensions >=4.2.0
    - python >={{ python_min }}
    - absl-py >=0.9.0
    - typing-extensions >=4.2.0
    - jax >=0.4.27
    - jaxlib >=0.4.27
    - numpy >=1.24.1
    - toolz >=0.9.0

test:
  imports:
    - chex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepmind/chex
  summary: 'Chex: Testing made fun, in JAX!'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - PhilipVinc
    - hbq1
