{% set name = "chex" %}
{% set version = "0.1.85" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chex-{{ version }}.tar.gz
  sha256: a27cfe87119d6e1fe24ccc1438a59195e6dc1d6e0e10099fcf618c3f64771faf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolatio

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - absl-py >=0.9.0
    - typing-extensions >=4.2.0
    - jax >=0.4.16
    - jaxlib >=0.1.37
    - numpy >=1.24.1
    - toolz >=0.9.0

test:
  imports:
    - chex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/chex
  summary: 'Chex: Testing made fun, in JAX!'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - PhilipVinc
    - hbq1
