{% set name = "chex" %}
{% set version = "0.1.88" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chex-{{ version }}.tar.gz
  sha256: 565de897b1373232cdfca5e699f50fa49403d2c7d23f6c5a75a97ef713d2fe36

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolatio

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - typing_extensions >=4.2.0
    - python >=3.9
    - absl-py >=0.9.0
    - typing-extensions >=4.2.0
    - jax >=0.4.27
    - jaxlib >=0.4.27
    - numpy >=1.24.1
    - toolz >=0.9.0

test:
  imports:
    - chex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/chex
  summary: 'Chex: Testing made fun, in JAX!'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - PhilipVinc
    - hbq1
