{% set name = "chex" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chex-{{ version }}.tar.gz
  sha256: adb5d2352b5f0d248ccf594be1b1bf9ee7a2bee2a57f0eac78547538d479b0e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - absl-py >=0.9.0
    - dm-tree >=0.1.5
    - jax >=0.1.55
    - jaxlib >=0.1.37
    - numpy >=1.18.0
    - toolz >=0.9.0
    - typing_extensions >=4.2.0

test:
  imports:
    - chex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/chex
  summary: 'Chex: Testing made fun, in JAX!'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PhilipVinc
    - hbq1
